### ISSUE TITLE
[BUG] Compatibity with Automated Animations broke in 0.8.x

### ISSUE THREAD

**Issue by Naitbit** [Moerill/fvtt-mars-5e#101]
It would be cool if Mars 5e worked with https://github.com/otigon/automated-jb2a-animations

When tested with Foundry 0.86, dnD5e 1.3.3, Automated Animations 0.3.63, Mars 5e 1.6.1 I did not manage to get it working (it works fine with Mars 5e disabled).

**Describe the solution you'd like**
Option 1: Add Automated Animation to known incompatibilities https://github.com/Moerill/fvtt-mars-5e/issues/50
Option 2: Add compatibility with Automated Animation
Option 3: tell me that it is AA issue not Mars 5e so I should report it there instead :)

**Comment by Moerill** [comment]
This is (or more was) a feature already. I haven't checked it for 0.8.x since it wasn't updated when i updated mars and i didn't have time since to check it.  
So that said, this will get fixed when i finally get around to fix all 0.8.x bugs that surfaced for mars.
