### ISSUE TITLE
As GM cant Apply Damage when Players Hit

### ISSUE THREAD

**Issue by Thinstardust** [Moerill/fvtt-mars-5e#104]
When players hit in combat the apply damage button does not function.  If the I(The GM) roll as the character and hit, I can apply damage, but when a player rolls and hits and I(The GM) go to apply damage, the damage does not apply.

Maybe it is not a bug.  Maybe I am doing something wrong.  I never had a problem before

Using Foundry 8.6
Mars 5e 1,6,2
DnD 5e 1.3.3

**Comment by Moerill** [comment]
Hi, thanks for your bug report.  
Since your bug report is missing some important information, please resubmit it following the issue template for bug reports.
