### ISSUE TITLE
[FEATURE] PF2E compatibility

### ISSUE THREAD

**Issue by PupperooX** [Moerill/fvtt-mars-5e#12]
Is there a chance this could get PF2E compatibility?
It's easily my favourite rolling mod + I wouldn't mind donating to help nudge it along

**Comment by Moerill** [comment]
It is *highly* unlikely. 
The only chance of this happening would be my group switching to PF2E, which isn't likely in the near future. (Or someone sending a PR, or taking this code and making it work with PF2E)

(PF2E is a highly complex system, so its not a small change, i'd guess.)

**Comment by Moerill** [comment]
I forgot to thank you for your nice words and good intentions! :heart:

**Comment by MrVauxs** [comment]
I will add that [PF2e Quickrolls](https://gitlab.com/mcarthur.alford/pf2qr) gives a very basic (and that's a good thing in my eyes) automation when it comes to rolls.
![](https://gitlab.com/mcarthur.alford/pf2qr/-/raw/master/readme-resources/quick-targeting.gif)
