### ISSUE TITLE
[BUG] Formatting in Chat-Card "broken"

### ISSUE THREAD

**Issue by tagnullde** [Moerill/fvtt-mars-5e#13]
When rolling the Attack / Damage for "Spiritual Weapon" the text formatting is a bit broken.
It happens regardless of an token is targeted or not. Happens regardless of other modules being disabled or not.

Foundry: 0.7.8
DnD5e: 1.2.0
Module: 0.2.2
No error on console

![css-off](https://user-images.githubusercontent.com/44159008/102651214-73341a80-416c-11eb-9006-72f6bd2cda85.png)

**Comment by Moerill** [comment]
Is it the srd spiritual weapon? (if it exists)
if not, could you please post the configuratoins from the item sheet?

**Comment by Moerill** [comment]
ah nvm i can reproduce it. will take a proper look at what is causing this tomorrow

**Comment by Moerill** [comment]
nvm fixed it :sweat_smile:
