### ISSUE TITLE
[FEATURE] integration with other rolling modules like Dice so Nice, Sadness chan?

### ISSUE THREAD

**Issue by JawayWu** [Moerill/fvtt-mars-5e#14]
Hi, I love your module and all its features. I was wondering if it was possible or if you'd ever consider making it compatible with Dice so Nice (3D dice rolls) and Sadness chan (tracks roll statistics).

**Comment by Moerill** [comment]
Sadness Chan, i need to take a look at, but DsN can and probably will be done in the (near) future.

**Comment by Moerill** [comment]
Dice So Nice support is integrated now.
Sadness Chan is kinda unlikely that it will happen.
