### ISSUE TITLE
[BUG] Random blur effect with chat cards

### ISSUE THREAD

**Issue by Riplae** [Moerill/fvtt-mars-5e#15]
Just added the mod, running foundryvtt version 0.7.8 and 5e version 1.2.0
For some reason Mars keeps adding a really jarring blur effect on the cards and I'm not exactly sure what to do. I uninstalled all mods and only ran Mars 5e but that didn't seem to help either.
![bug](https://user-images.githubusercontent.com/76232707/102674130-b16c1280-4149-11eb-9960-48bc2423cd09.PNG)

**Comment by Moerill** [comment]
for future bug reports please follow the issue template provided.
while your screenshot is helpful you're missing crucial information (like the browser used!)
see the bug report for the same issue: https://github.com/Moerill/fvtt-mars-5e/issues/16 how the bug report should've looked like.
