### ISSUE TITLE
[BUG] Parts of cards get blurred as chat log scrolls (desktop app)

### ISSUE THREAD

**Issue by crash1115** [Moerill/fvtt-mars-5e#16]
**Describe the bug**
When attack cards are present in the chat log, scrolling past them produces an odd visual bug where portions of the card are blurred out. This seems to occur once the cards pass above a set height on the screen, and only occurs in the desktop app

**To Reproduce**
1. Open up Foundry in the desktop app
2. Roll a bunch of attacks
3. Scroll up and down in the chat log
3. Observe weirdness

**Expected behavior**
To be able to scroll and read all parts of the chat cards as I do so.

**Module incompatibilities**
This happens even with no mods enabled.

**Screenshots/GIFs/Videos**
https://i.gyazo.com/56ba31317fd8824c9ea8802e296d0ca7.mp4

**Desktop (please complete the following information):**
 - Windows
- Desktop app
- Foundry 0.7.8
- Dnd5e 1.2.9
- Mars 0.2.3

**Additional context**
Seems to work fine in Chrome.

**Comment by crash1115** [comment]
Whoops, didn't see this one got created while I was making this report: https://github.com/Moerill/fvtt-mars-5e/issues/15

Looks like the same issue.

**Comment by Moerill** [comment]
Thanks for the good bug report!
It seems to be some issue with the fvtt apps css engine <_<
but found the bug and will fix it for the next update...
