### ISSUE TITLE
[BUG] Damage modifiers take into account resistance but not immunity by default

### ISSUE THREAD

**Issue by crash1115** [Moerill/fvtt-mars-5e#17]
**Describe the bug**
 Damage modifiers on cards correctly default to 1/2 when the target is resistant to a type of damage. They do not default to 0 when the target is immune to a type of damage. No errors get thrown.

**To Reproduce**
1. Set up a token with immunity to a specific type of damage
2. Set up a weapon or spell attack that does that type of damage
3. Attack that token with that weapon. If the attack doesn't hit, override it so it does hit.
4. Roll damage.
5. Observe that the default damage modifier for the immune damage is not zero.

**Expected behavior**
The damage modifier next to the type of immune damage to be automatically set to zero.

**Module incompatibilities**
Occurs without any other mods installed.

**Screenshots/GIFs/Videos**
![image](https://user-images.githubusercontent.com/41387713/102676545-18022800-416c-11eb-9274-bebc5e9877fb.png)

**Desktop (please complete the following information):**
- Windows
- Desktop app, Chrome
- Foundry 0.7.8
- Dnd5e 1.2.9
- Mars 0.2.3

**Additional context**
N/A

**Comment by Moerill** [comment]
Thanks for the good bug report!
should be fixed with next update
