### ISSUE TITLE
[BUG] Rolling a tool throws dice term errors

### ISSUE THREAD

**Issue by crash1115** [Moerill/fvtt-mars-5e#19]
**Describe the bug**
When using a tool, the card is displayed, but clicking on the formula in the card to make the actual roll fails. The console shows the error in the screenshots section below. This occurs when rolling normally, and with dis/advantage

**To Reproduce**
1. Add a tool to an actor's inventory (I used SRD thieves tools)
2. Roll the tool from the character sheet
3. Click the formula in the card
4. Observe that nothing happens.

**Expected behavior**
Clicking the roll formula will roll the item.

**Module incompatibilities**
Occurs without any other mods installed.

**Screenshots/GIFs/Videos**
![image](https://user-images.githubusercontent.com/41387713/102677887-ae394c80-4172-11eb-84e5-7ffaefafa675.png)

**Desktop (please complete the following information):**
- Windows
- Desktop app, Chrome
- Foundry 0.7.8
- Dnd5e 1.2.9
- Mars 0.2.3

**Additional context**
N/A

**Comment by Moerill** [comment]
fixed for next release
