### ISSUE TITLE
[BUG] Pop Out Message displays roll details to players

### ISSUE THREAD

**Issue by Naitbit** [Moerill/fvtt-mars-5e#25]
Player right clicking on chat message and selecting "Pop Out Message" will get not sanitized message that was supposed to be GM only:
![obraz](https://user-images.githubusercontent.com/4226039/102710321-66691100-42a9-11eb-8143-5821a78cdb13.png)

**To Reproduce**
1. Make a roll as GM
2. As a player right click the message
3. Select "Pop Out Message"
Now as a player you see all roll details

**Expected behavior**
Popup message should look the way it does in main chat

**Desktop:**
 - OS: AWS Ubuntu
 - Browser: tested on both Firefox and Chromium
 - FVTT Version 0.7.8
 - Module version 0.3.0

**Comment by Moerill** [comment]
oh, didn't even think of popout messages  
i'd actually probably just disable them being popout, since there is (imo) not much use in it for this kind of cards (unlike regular dnd5e cards that have "reusable" buttons)

**Comment by Moerill** [comment]
Yep, removed the popouts for the new update!
