### ISSUE TITLE
[BUG] saving throw/ability roll issue when modifier is 0

### ISSUE THREAD

**Issue by Naitbit** [Moerill/fvtt-mars-5e#26]
When making a saving throw for NPC/player character exception occurs if saving throw modifier is 0:
If modifier is non zero saving throw appear to work.

```
SyntaxError: expected expression, got '}'
    _safeEval http://<redacted>/scripts/foundry.js:8057
    evaluate http://<redacted>//scripts/foundry.js:7671
    roll http://<redacted>//scripts/foundry.js:7701
    _roll http://<redacted>//systems/dnd5e/module/dice.js:100
    d20Roll http://<redacted>//systems/dnd5e/module/dice.js:124
    rollAbilitySave http://<redacted>//systems/dnd5e/module/actor/entity.js:825
    rollAbilitySave http://<redacted>//modules/mars-5e/js/actor/entity.js:40
    callback http://<redacted>//systems/dnd5e/module/actor/entity.js:723
    submit http://<redacted>//scripts/foundry.js:13119
    _onClickButton http://<redacted>//scripts/foundry.js:13082
    jQuery 2
dice.js:102:15
```

![screenshot](https://user-images.githubusercontent.com/4226039/102711788-2e1b0000-42b4-11eb-805f-2600cfba7b18.png)

Happens also when I disable all other modules

**Desktop:**
 - host OS: AWS Ubuntu
 - Browser: Firefox 84 run on Ubuntu 20.04
 - FVTT Version 0.7.8
-  DnD version: 1.2.0
 - Module version 0.3.0

**Comment by Moerill** [comment]
As for the first part:
*currently* no auto targeting using the template is supported. I am waiting for the next (i think) DnD5e update/patch to drop, then it will be supported (automatically for this module)

For the saving throws failing.. i'll take a look what happened there.

An important note: I#d suggest you remove your URL from error reports, just to be safe!

**Comment by Naitbit** [comment]
URLs were already partially sanitized (with big chunk removed) :) . Thanks for taking a look!

**Comment by Moerill** [comment]
I cannot reproduce this.
So ignoring the template not automatically targeting issue, you're not able to throw savingthrows in general for which type of actor?

**Comment by Moerill** [comment]
other possibly needed information:
- does it fail with every actor?
- which dnd version do you have installed?
- does it happen only after an AoE spell was placed?

**Comment by Naitbit** [comment]
It seems that it fails when saving throw modifier is 0, works otherwise.
I did test with regular Crab first
![obraz](https://user-images.githubusercontent.com/4226039/102717303-5d903380-42d9-11eb-837b-46eec137299f.png)
but reproduced it later with different tokens. If Modifier is non zero it seems to work.

**Comment by Naitbit** [comment]
Just for completion sake: I did verify that saving throws with mars-5e off do work.
I don't think it is AoE relevant after all.
DnD version: 1.2.0
![obraz](https://user-images.githubusercontent.com/4226039/102717352-aea02780-42d9-11eb-9465-83fe7ef5e954.png)

**Comment by Moerill** [comment]
quick question:
do you have *any* messages in the chat?

**Comment by Moerill** [comment]
(ok i may be wrong about this - i found another error i think)

Regarding your issue: i can't detect your error at all, still.
what i did.
create a new world
move the crab form the srd compendium onto the map
click constitution saving throw

no error is thrown

**Comment by Naitbit** [comment]
No message in chat, just error banner instead:
![obraz](https://user-images.githubusercontent.com/4226039/102717978-7864a700-42dd-11eb-9051-9f589960df80.png)

**Comment by Naitbit** [comment]
There is secondary error after the first one:
```
Uncaught (in promise) TypeError: roll is null
    _renderRoll http://<redacted>/modules/mars-5e/js/actor/entity.js:67
entity.js:67:11
```
but it seems to be caused by the first one.

**Comment by Moerill** [comment]
its so weird
the first issue sounds like its not mine, more like a default dnd issue. (Cause all i'm doing is calling a dnd core method there)
have you tried this in a new / another worlds as well? i'm kind of clueless atm

**Comment by Naitbit** [comment]
It looks like no modifier ends up being a empty string `""` instead of `0` and gets concatenated to expression:
![obraz](https://user-images.githubusercontent.com/4226039/102718059-fe80ed80-42dd-11eb-9ed6-6b5d3f44f131.png)

(I didn't look at the code at all so I may be wrong).

(This time it is with sandbox plugin enabled, but it is not necessary to get this problem)

**Comment by Naitbit** [comment]
When I turn off the Mars 5e default dnd5e roll works. I may try the new world if you want or walk through it with debugger if it is more useful.

**Comment by Moerill** [comment]
ooooooooooh thats valuable information
i *may* know whats causing it, even though i'm confused it doesn't result in an error for me

**Comment by Naitbit** [comment]
With Mars:
Roll._formula ends up being "1d20+"

![WithMars5e](https://user-images.githubusercontent.com/4226039/102718584-da72db80-42e0-11eb-97d3-6d28c9c64539.png)

 instead of default:
 "1d20+0"
 
![obraz](https://user-images.githubusercontent.com/4226039/102718605-ef4f6f00-42e0-11eb-8b67-f863d6e17d42.png)

though I'm also not sure why it is empy string instead of  0 in my case. Stacktraces are slightly different (default  behaviour  creates a dialog asking for Adventage/Normal/Disadventage) and I'm only now starting to familiarize myself with the code.

**Comment by Naitbit** [comment]
My guess would be that problem is somewhere around Mars5eRoll _splitDiceTerms.
We get terms from formula that look fine beforehand:
![obraz](https://user-images.githubusercontent.com/4226039/102719381-b665c900-42e5-11eb-9d41-4971cb482d9d.png)

but then 
`if (e instanceof NumberTerm && e.number === 0 && !e.flavor) return "";`
replaces last part into empty string.

![obraz](https://user-images.githubusercontent.com/4226039/102719410-de552c80-42e5-11eb-9916-d0aab723e187.png)


This probably does not help you much, but I though I will share in case there is some parameter that is different on your end which makes reproduction harder.

**Comment by Moerill** [comment]
thanks for investigating!
i did think as well that that *could* be the issue too
but its stil weird that it works here but not for you :grimacing: 
i'll fix that part up and hope it fixes it for you..

**Comment by Moerill** [comment]
So ye, i pushed an update. Please check fi this fixes it for you and report back!

**Comment by Naitbit** [comment]
Made a quick check and it works. :+1: 
Crabs are back on menu :crab: :laughing: . Thanks for the excellent fixup speed!

**Comment by Moerill** [comment]
yay! Thanks for the deep dive error checking!
