### ISSUE TITLE
[BUG] Errors casting with Token Action HUD

### ISSUE THREAD

**Issue by cwrinn** [Moerill/fvtt-mars-5e#27]
**To Reproduce**
1. Cast from Token Action HUD
4. See error in console

**Error**
> Uncaught (in promise) TypeError: usage.get is not a function at Mars5eActor.useSpell

**Module incompatibilities**
- Token Action HUD

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Chrome 86.0.4240.199
 - FVTT Version 0.7.8 and 0.7.9
 - Module version 0.3.1

**Additional context**
I have a pull request incoming that solved it for me. First, TAH module is using a deprecated method (useSpell). But in that method, you seem to be expecting `usage` to be a Map when it is just an Object.

**Comment by Moerill** [comment]
Ye as commented in the merge request:
The method causing trouble is not supposed to be there anymore, since its deprecated in 5e.
But this also means you should probably file a PR or issue on token action hud to not use it anymore as well.
