### ISSUE TITLE
[BUG] Error using melee weapon with Midi-QOL

### ISSUE THREAD

**Issue by cwrinn** [Moerill/fvtt-mars-5e#29]
**Describe the bug**
Also post console errors (F12 for most browsers) here that occur.

**To Reproduce**
1. Use melee weapon with Midi-QOL enabled

**Expected behavior**

**Module incompatibilities**
- Midi-QOL

**Screenshots/GIFs/Videos**
> A picture is worth a thousand words.
![image](https://user-images.githubusercontent.com/46600/102747363-c69d9880-4325-11eb-83be-0aeb64530030.png)

**Desktop (please complete the following information):**
 - OS:ChromeOS
 - Browser Chrome 86
 - FVTT Version 0.7.8
 - Module version 0.3.1

**Comment by Moerill** [comment]
Thanks for the bug report.
But the question would be which kind of settings you're using with MidiQoL that causes this issue. (Depending on the setting it may or may not be fixed)

**Comment by Moerill** [comment]
See: https://github.com/Moerill/fvtt-mars-5e/issues/10#issuecomment-749528287
