### ISSUE TITLE
[BUG] Chat Card renders before Spell Template selects targets

### ISSUE THREAD

**Issue by cwrinn** [Moerill/fvtt-mars-5e#30]
**Describe the bug**
With MESS and MARS installed, if you try to target using spell templates, the targets selected are not what appear on the chat card. This is likely because the chat card renders before the spell template is drawn.

**Expected behavior**
The chat card should show the selected targets after placing the spell template.

**Screenshots/GIFs/Videos**
![image](https://user-images.githubusercontent.com/46600/102753465-f2724b80-4330-11eb-8974-fbd98d550935.png)

**Additional context**
The AoE targeting using spell templates is very helpful and the MARS chat card is a great time saver. These two features should work well together.

**Comment by Moerill** [comment]
yep that won't work, atm.
this will be fixed (and part of Mars) with the next 5e update, since i need smth to be done there first.
This will also happen "automatically" since the parts are in the module already, 5e just needs to update. (The merge is already in)

**Comment by Moerill** [comment]
(actually i hope that mars and mess won't collide there..)
