### ISSUE TITLE
[BUG] NaN while subtracting hitpoint on AOE Spell (Fire Breath)

### ISSUE THREAD

**Issue by tagnullde** [Moerill/fvtt-mars-5e#31]
How to reproduce:

1. Get 2 PC Token on the Map
2. Get 1 Hellhound Token on the Map
3. Select both PC Tokens as targets
4. Blast both PC Tokens with "Fire Breath"
5. Roll Damage
6. Auto-Reduce Hitpoints
7.  Observe "NaN" being subtracted leaving the Token at  "Empty" Hitpoints

DND 1.2.0
VTT: 0.7.9
Module: 0.3.3
Console shows (maybe unrelated?) Error (see screenshot)

FYI: Screenshot was taken with Module Version 0.3.2 - but issue is still present in 0.3.3.

![NaN-Bug](https://user-images.githubusercontent.com/44159008/102901944-8564d000-446e-11eb-96dd-b41857aab3e1.PNG)

**Comment by Moerill** [comment]
Foudn the issue (i think)
Does it only happen if you first threw the saving throws and *then* throw the damage?

**Comment by tagnullde** [comment]
Yes. I rolled the saving throws first when it happened.
While testing it by rolling the **damage first** (hence auto-rolling the saving-throw) it works as expected.

**Comment by Moerill** [comment]
Fixed for next update
