### ISSUE TITLE
[BUG] Quick-Bar not "finding" weapon in character-sheet

### ISSUE THREAD

**Issue by tagnullde** [Moerill/fvtt-mars-5e#32]
Steps to reproduce:

1. Drag Weapon into Quick-Bar.
2. Attack via Quick-Bar
3. Observe error-message (see screenshot)

DND 1.2.0
VTT: 0.7.9
Module: 0.3.3
No errors in console

![No-Mace](https://user-images.githubusercontent.com/44159008/102903658-ed1c1a80-4470-11eb-9108-b36b78eec686.PNG)

**Comment by Moerill** [comment]
That is not an issue with Mars, since it does nothing regarding that interactiotn. Or at least i'm 99% sure.
Test it without mars.
Are you sure you selected  the actors token when clicking the weapon?

**Comment by tagnullde** [comment]
Nevermind. After reopening the charsheet everthing worked fine. I was a bit too quick with this one.
Sorry.
