### ISSUE TITLE
Automatic template targeting not working

### ISSUE THREAD

**Issue by davelamorte** [Moerill/fvtt-mars-5e#34]
**Describe the bug**
I know in the notes it says you need DND 5e 1.2.1 to make this work, but the latest version is 1.2.0: does it mean we have to wait until 1.2.1 comes up? If that is indeed the reason, please just let me know and consider the bug void.

**To Reproduce**
When you launch a spell with a targeting template, instead of waiting for you to place the template, it writes in the chat the launched spell using whatever you had already selected before as targeting (or none if you had nothing).
Once you do place the template, you correctly see the new selection of targets, but the GM does not receive this update; also, the spell doesn't change: if it was "none", it remains "none", if it was previous targets, it remains on those targets.

The only workaround that I have found is to launch the spell without consuming a spell slot, only to place the template, and then launching it again without the template to do the actual spell on the wanted targets.

**Expected behavior**
Targets should be applied in the first launch of the spell.

**Module incompatibilities**
I've tried stripping down the world to no modules, only yours were active, with no difference in result.

**Desktop:**
Windows / Chrome latest updates
Foundry 0.7.9
DND 5e 1.2.0
Mars 5e 0.3.3
MESS 0.13.0

PS: from me and all my players, thank you for your incredible work!

**Comment by Moerill** [comment]
yep, you gotta wait for DnD 1.2.1.

**Comment by Moerill** [comment]
> PS: from me and all my players, thank you for your incredible work!

Ah and thanks for the nice words! (:
