### ISSUE TITLE
[BUG] Magic Missile-like items not rolling damage

### ISSUE THREAD

**Issue by Alexis-Grimm** [Moerill/fvtt-mars-5e#40]
**Describe the bug**
When using items or spells that don't have saving throws or attack rolls (the "other" type), such as magic missile, the chat card appears completely blank, with no option for rolling damage.
Also post console errors (F12 for most browsers) here that occur.

**To Reproduce**
1. Create item with action type "other"
2. Add a damage formula and type
3. Roll item

**Expected behavior**
I would expect to see the normal chat card, with the option to roll damage, and no options for saving throws or attack rolls.

**Screenshots/GIFs/Videos**
![magicMissile](https://user-images.githubusercontent.com/23371612/103396216-eab86100-4aff-11eb-9b45-3fbe095d28cb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: FVTT Application, no browser
 - FVTT Version 0.7.9
 - Module version 0.3.3

**Comment by Moerill** [comment]
Thanks for the bug report!
fixed for next version

**Comment by Moerill** [comment]
although.. fixed is kind of relative
not sure how to properly handle magic missile, it will "work" but not in a perfect way..

**Comment by Moerill** [comment]
The solution for this i chose now is the "reapply without using resources button". This way once can cast magic missile once, then reapply to each target as often as one hits them with one of your missiles.
