### ISSUE TITLE
[DOCUMENTATION] incompatibility with module Multiattack-5e 

### ISSUE THREAD

**Issue by davidR1974** [Moerill/fvtt-mars-5e#41]
**Describe the bug**
Incompatbility with module MultiAttack-5e

**Module incompatibilities**
The MultiAttack-5e (https://github.com/jessev14/Multiattack-5e) interfers with MARS-5e : no action happens when clicking on items and the following message appears in console :

override.js:491 Uncaught (in promise) TypeError: Cannot read property 'altKey' of null
    at damageRollMA5e (override.js:491)
    at Item5e.rollDamageMA5e (override.js:435)
    at MarsItem5e.rollDamage (entity.js:257)
    at MarsItem5e._getTemplateData (entity.js:118)
    at async MarsItem5e.displayCard (entity.js:13)

Deactivating module Multiattack-5e solve the issue completely.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser : tested on "server side"
 - FVTT Version : 0.7.9 (with Plutonium 0.2.0 and dnd5e 1.2.0)
 - Module version : 1.1.0

**Additional context**

**Comment by davidR1974** [comment]
Great job on the whole module. .. I wanted to tag this as "documentation" but was not able to find where to change the tag....

**Comment by Moerill** [comment]
Linked to this issue in known module incompatibilties. Will close this, which does not mean its getting resolved, just that i don't want it in the open issue list..
