### ISSUE TITLE
[BUG] Showing Dice so Nice! rolls for NPCs

### ISSUE THREAD

**Issue by 9ryex5** [Moerill/fvtt-mars-5e#44]
![image](https://user-images.githubusercontent.com/43207603/103668945-a699e600-4f6f-11eb-8191-62f2a5d8f7ef.png)
Even with this Dice So Nice! feature enabled, fvtt-mars-5e will show 3D dice when rolling for NPCs.

The expected behavior is for players not to see 3D dice from NPC rolls.

**Comment by Moerill** [comment]
Thanks for the bug report!
note to myself:
```JS
game.settings.get("dice-so-nice", "hideNpcRolls")
```
