### ISSUE TITLE
[BUG] Class features like Sneak Attack not working

### ISSUE THREAD

**Issue by FelBai** [Moerill/fvtt-mars-5e#46]
Foundry Version 0.7.9
DND Version: 1.2.0

Active Modules: 
mars-5e--v1.1.0;
mess--v0.13.0;
tidy-ui_game-settings--v0.1.21;

When clicking on sneak Attack no role appears in Chat. 
Spell like Magic Missle also not appears.

**Comment by Moerill** [comment]
Please provide screenshots of the items Details Tab, cause there are like a million ways to configure those.

**Comment by FelBai** [comment]
![grafik](https://user-images.githubusercontent.com/63197071/103764792-66447180-501c-11eb-90a9-dac64a68c368.png)
