### ISSUE TITLE
[FEATURE] Add option to disable Tooltip

### ISSUE THREAD

**Issue by tagnullde** [Moerill/fvtt-mars-5e#52]
When hovering over an item you show a Tooltip "(Right Click to toggle (dis-)advantage)". 

Could you **provide an option to disable this Tooltip** because a lot of times it stacks with the roll-style Tooltip (Normal, Advantage, Disadvange) and it's a bit anoying not being able to see the mode you are in without moving the mouse a back and forth.
It Gridview in Tidy5e Sheet it also blocks some of the item text.

![Screenshot at 2021-01-08 17-48-48](https://user-images.githubusercontent.com/44159008/104041774-d0eedc00-51d9-11eb-9067-319462300cd1.png)

Thanks!

**Comment by Moerill** [comment]
This is more of a bug than a feature request.
i will not a dd a setting to disable the hint, but:
a) i fixed the styling getting broken for tidy5es grid layout
b) on grid layout always display the tooltip to the right of the icon.

(coming next patch)
