### ISSUE TITLE
[BUG] DAE ternary operators do not work with Mars activated.

### ISSUE THREAD

**Issue by JLtheking2** [Moerill/fvtt-mars-5e#55]
Sorry again for reopening the same ticket. The ternary operators bug wasn't fixed with the new update.

Tried again with a clean install. Mods activated: TidyUI, TidySheet, DAE, libWrapper.

Just added a simple active effect directly to a character that overrides AC.

![image](https://user-images.githubusercontent.com/48344299/104095816-e0525000-52d3-11eb-9ce7-0836445de721.png)

Now with Mars activated:

![image](https://user-images.githubusercontent.com/48344299/104095835-f9f39780-52d3-11eb-9b45-7814f0b0e43e.png)

There does not seem to be any console errors. 

FVTT 0.7.9
5e System 1.2.2
DAE 0.2.33
Mars 1.2.0
(All latest as of the time of this post)

**Comment by Moerill** [comment]
oh did i break it again after fixing it? :thinking: :see_no_evil:

**Comment by Moerill** [comment]
So i was wrong with my assumption - wondering why it worked at some point.
Bigger issue was i was manipulating the formula in a way DAE doesn't like.. i added a small exception to check for ternary operations and hope that it works now..
Please report back, won't close this issue before that.

**Comment by JLtheking2** [comment]
So another small issue: the AC formula generated by DAE, "@abilities.dex.mod > 3 ? 3 + 13 : @abilities.dex.mod + 13" still fails to resolve. DAE generates this formula for an armor that grants an AC of 13 and has a Max. Dexterity Modifier of 3, as the whole point of the shebang is to take the armor dex cap into account, such as for the vanilla 5e medium armors.

![image](https://user-images.githubusercontent.com/48344299/104121572-4b566200-537a-11eb-8fa3-62a86b428e37.png)

I played around a bit more with the formula, and I found out that if I put parentheses around the middle phrase:
@abilities.dex.mod > 3 ? (3 + 13) : @abilities.dex.mod + 13

![image](https://user-images.githubusercontent.com/48344299/104121700-4c3bc380-537b-11eb-82ad-51f316c6c257.png)

It resolves correctly. Modifying the dex value of the character correctly modifies the AC as you would expect.

So perhaps this can be a quick and dirty fix on your end to at least get the automatic AC calculation of DAE working?

**Comment by Moerill** [comment]
Wow, why it calculating it like that and not like "(@abilities.dex.mod > 3 ? 3 : @abilities.dex.mod) + 13"? (which is the case i tested...  (and less 13's used ..) 
but ye i'll look into it, thanks for testing

**Comment by JLtheking2** [comment]
Yes yours make sense too, but ultimately we just have to find a way to get it working with DAE’s formula haha.

**Comment by Moerill** [comment]
next try! that formula above works now..

if you find any other issues, please report back here!
If not.. please do as well, so we can close this issue!

**Comment by JLtheking2** [comment]
Apologies for the delay. Yes, the formula is indeed working! :) Cheers and thank you!

**Comment by Moerill** [comment]
yay!
and no problem regarding the delays! Always take the time you need, these are non pressing matters.

If you encounter any other DAE issue, please open a new issue and i'll see what i can do!
