### ISSUE TITLE
[BUG] Short rest chat output

### ISSUE THREAD

**Issue by 9ryex5** [Moerill/fvtt-mars-5e#60]
Calculations are perfect, but GM and players see this in chat doing a short rest.

![image](https://user-images.githubusercontent.com/43207603/104249535-8aacad80-5463-11eb-96e1-0565ca8cdd86.png)

**Comment by Moerill** [comment]
This is no bug, its exactly as intended. (and a .. non mentioned mars feature)  
mars adds all replaced data attributes as dice flavor text, so one knows where the "magic numbers" come from. In case of hit die its the constitution modifier. This also translates to regular roll card design. (Which will ger replaced soonish with Mars one to make everything look more consistent.)
