### ISSUE TITLE
[FEATURE] Setting for Right-Click (Dis)Advantage

### ISSUE THREAD

**Issue by Grygon** [Moerill/fvtt-mars-5e#67]
**Is your feature request related to a problem? Please describe.**
I love most of what this module does, but the fact that I can't disable the (dis)advantage switch on right click is frustrating me--it's not a feature I'm super interested in using, since I can ctrl/shift-click, and it gets in the way of a lot of other things that use right click.

**Describe the solution you'd like**
A setting to control whether right click sets up (dis)advantage

**Describe alternatives you've considered**
Uninstalling Mars--which I don't want to do, I love it!

**Additional context**
Looks like the ctrl/shift-click is new, so makes sense this wasn't implemented before!

**Comment by PaulAshcroft** [comment]
umm, i actually like the feature as sometimes players forget to setup the (dis)advantage before the roll comes up in chat.

**Comment by Grygon** [comment]
Yeah I definitely see the use for it, I'd definitely want to use it if I didn't have other things using right click. I've also had some issues with my players forgetting they left their roll on (dis)advantage, and having to re-roll--although I'm sure they'd get used to it eventually.

I guess I'll see about a PR in the near future and disable MARS until then!

**Comment by quantized-omega** [comment]
My 2 cents on this issue.
Using Tidy5e character sheet. When I need to interact with an item and right click on it in order to edit it, unfortunately it also triggers the right-click function of Mars5e module re adv/dis/normal. 
That makes functionality a bit touch and go, as it sometimes inadvertently results in changing the current state of (dis)advantage for the item.

**Comment by Moerill** [comment]
> Using Tidy5e character sheet. When I need to interact with an item and right click on it in order to edit it, unfortunately it also triggers the right-click function of Mars5e module re adv/dis/normal.

Tidy got an option to replace right click menu with a "real" menu button
