### ISSUE TITLE
[BUG] [FEATURE] Calling the actors rollAbilityTest, rollAbilitySave, and rollSkill functions no longer returns a Roll

### ISSUE THREAD

**Issue by ironmonk88** [Moerill/fvtt-mars-5e#77]
I have a module that uses the actors rollAbilityTest, rollAbilitySave, and rollSkill functions.  I pass in { chatMessage:false} so that a chat message isn't created and use the roll that it returns.

Unfortunately I get back a Mars5eMessage when the Mars5e module is active.  Which I could work around if it also contained the roll information.  I noticed that the _roll property of the Mars5eMessage is null and was wondering if that's supposed to be filled in?
Ultimately could it be filled in?  And I'd also love it if the Mars5eMessage looked at the chatMessage=false options being passed in and not create a new chat message.

Thank you.

**Comment by Moerill** [comment]
>  And I'd also love it if the Mars5eMessage looked at the chatMessage=false options being passed in and not create a new chat message.

Thats.. an oversight, thanks, will take a look

>  I noticed that the _roll property of the Mars5eMessage is null and was wondering if that's supposed to be filled in?

Nope its not supposed to be filled in. That part is working as intended

**Comment by ironmonk88** [comment]
Is it possible to get access to the roll data once the message is returned?

**Comment by Moerill** [comment]
Currently not easily, no. But i may think of rethinking my strategy here, soon, when i got time to work on it again.

**Comment by ironmonk88** [comment]
I noticed for rollAbilitySave you have 'options.fromMars5eChatCard' that bypasses the code and goes straight to the original function.  This works perfectly for my module.  Probably not what you intended it to be used for.  :-) But would it be possible to add that to rollAbilityTest, and rollSkill as well?  That would totally solve my issue.
