### ISSUE TITLE
[BUG] module is not working at all in Foundry 0.7.9 at all

### ISSUE THREAD

**Issue by mikkosaarinen** [Moerill/fvtt-mars-5e#78]
Hello

Installed both mess and mars, but they don't appear in the manage modules list in Foundry 0.7.9
Moreover, I cannot see any functionality for either of these modules in game.

I tried to uninstall and install again, but didn't help.
Will try later today by uninstalling other modules to see if there is a conflict with something.

**Comment by Moerill** [comment]
Please follow the issue template to provide needed information. A bug report like this is not helpful at all, cause there is 0 information in it.  
Please create a new issue following the template.  

Also uninstalling modules shouldn't be the way to go, deactivating should be enough.
