### ISSUE TITLE
[Bug] Let ability checks respect roll mode "Self Roll"

### ISSUE THREAD

**Issue by 9ryex5** [Moerill/fvtt-mars-5e#81]
When an NPC rolls an ability check, it will show to players even if GM set rolls to self roll.
![image](https://user-images.githubusercontent.com/43207603/107230950-9914c780-6a17-11eb-922b-49eb12c89f7a.png)

The expected behavior would be the same as attack rolls, show to players if it's a public roll and hide from players if it's a self roll.

**Comment by Moerill** [comment]
Thanks for the report. This is kind of a bug report i think?
Going to take a look on what is going wrong there.
