### ISSUE TITLE
[FEATURE] Hide Weapon Descriptions by Default

### ISSUE THREAD

**Issue by MrVauxs** [Moerill/fvtt-mars-5e#90]
**Is your feature request related to a problem? Please describe.**
At higher levels, the items characters attack with start to have increasingly long descriptions on the account of being magic items. This spams the chat and also, whether that is a bug or a feature, even when you do hide the description, it appears again upon rolling the dice.

**Describe the solution you'd like**
Make an option to hide weapon descriptions by default, most likely User-only. And change/fix the issue of the description appearing once again when modifying the roll outcome.

It will not be harmful and actually beneficial to keep the general tags and traits of the weapon under said shortened description, as a means of still knowing what the weapon is besides the name:
![image](https://user-images.githubusercontent.com/32039708/110209243-ae9cd600-7e8b-11eb-882b-8e6db451db3a.png)

**Additional context**
Some examples:
![image](https://user-images.githubusercontent.com/32039708/110209206-71d0df00-7e8b-11eb-881b-372e220f4e64.png)
In this case, the weapon descriptions and traits fill the entire chat.
![image](https://user-images.githubusercontent.com/32039708/110209215-7eedce00-7e8b-11eb-839c-33fb2405f7df.png)
![image](https://user-images.githubusercontent.com/32039708/110209222-8ad99000-7e8b-11eb-8863-0840455436c1.png)

**Comment by Moerill** [comment]
> This spams the chat and also, whether that is a bug or a feature, even when you do hide the description, it appears again upon rolling the dice.

This was unintentional. It now correctly resets to the default style set for the 5e system here:  

![image](https://user-images.githubusercontent.com/26152015/112611581-4dc74480-8e1e-11eb-968f-4e38ac69628e.png)

Using that setting should fix this whole thing, i *think*. One kind of disadvantage still remains: It will always reset to the default on update (meaning: on rolling), buuut.. i don't want to go the extra mile of making this more complex remembering the states, etc.
